# Performance Benchmarking Script on Centos
# Author: Ozgur Gul (HPE)
# Date: 2021/04/29
# Version: 0.1 (Alpha)

trigger:
- '*'

pool:
  vmImage: ubuntu-latest

steps:
# Prepare the directory structure on VM-01  
- task: SSH@0
  inputs:
    sshEndpoint: 'vm01srvconn'
    runOptions: 'inline'
    inline: |
      sudo mkdir -p /data/benchmark
      sudo chown -R testadmin:testadmin /data/benchmark
      sudo chmod 2700 /data/benchmark
    readyTimeout: '20000'
# Prepare the directory structure on VM-02    
- task: SSH@0
  inputs:
    sshEndpoint: 'vm02srvconn'
    runOptions: 'inline'
    inline: |
      sudo mkdir -p /data/benchmark
      sudo chown -R testadmin:testadmin /data/benchmark
      sudo chmod 2700 /data/benchmark
    readyTimeout: '20000'
# CopyFilesOverSSH
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write for VM-01 Preparation
      HOST=51.132.25.102
      REMOTE_USER=testadmin

      # Pem file is too open
      chmod 0600 ./.ssh/terraform_rsa.pem
      
      ## REMOVE when ready
      ## ls -alR . 
      ## ssh -v -i ./.ssh/terraform_rsa.pem -o StrictHostKeyChecking=no $REMOTE_USER@ "date"
      
      ssh -q -i ./.ssh/terraform_rsa.pem -o StrictHostKeyChecking=no $REMOTE_USER@$HOST "date"
      
      # copy using ssh keys from agent to target machine
      scp -q -i ./.ssh/terraform_rsa.pem ./benchmark/  $REMOTE_USER@$HOST:/data/benchmark/


      # List the content 
      ssh -q -i ./.ssh/terraform_rsa.pem -o StrictHostKeyChecking=no $REMOTE_USER@$HOST "ls -al /data/benchmark"
      
      ssh -q -i ./.ssh/terraform_rsa.pem -o StrictHostKeyChecking=no -T $REMOTE_USER@$HOST <<'EOSSH'
      VAR1=`pwd`
      echo $VAR1

      VAR2=$(uname -a)
      echo $VAR2

      VAR3=$(id)
      echo $VAR3

      EOSSH

# - task: SSH@0
#   inputs:
#     sshEndpoint: 'vm01srvconn'
#     runOptions: 'inline'
#     inline: |
#       sudo chown -R root:root /data/benchmark/
#       sudo chmod -R 2700 /data/benchmark/
#       sudo chmod -R 700 /data/benchmark/
#     readyTimeout: '20000'
# - task: SSH@0
#   inputs:
#     sshEndpoint: 'vm02srvconn'
#     runOptions: 'inline'
#     inline: |
#       sudo chown -R root:root /data/benchmark/
#       sudo chmod -R 2700 /data/benchmark/
#       sudo chmod -R 700 /data/benchmark/
#     readyTimeout: '20000'
# - task: SSH@0
#   inputs:
#     sshEndpoint: 'vm02srvconn'
#     runOptions: 'inline'
#     inline: |
#       sudo chown -R root:root /data/benchmark/
#       sudo chmod -R 2700 /data/benchmark/
#       sudo chmod -R 700 /data/benchmark/
#     readyTimeout: '20000'
# - task: SSH@0
#   inputs:
#     sshEndpoint: 'vm02srvconn'
#     runOptions: 'commands'
#     commands: 'sudo iperf3 -s -p 8010 2>&1'
#     readyTimeout: '20000'

# - task: SSH@0
#   inputs:
#     sshEndpoint: 'vm01srvconn'
#     runOptions: 'script'
#     scriptPath: 'benchmark/perf_bench.sh'
#     readyTimeout: '20000'


