
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'vm01srvconn'
    runOptions: 'inline'
    inline: |
      sudo mkdir -p /data/benchmark
      sudo chown -R root:root /data/benchmark
      sudo chmod 2700 /data/benchmark
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'vm02srvconn'
    runOptions: 'inline'
    inline: |
      sudo mkdir -p /data/benchmark
      sudo chown -R root:root /data/benchmark
      sudo chmod 2700 /data/benchmark
    readyTimeout: '20000'

# CopyFilesOverSSH
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'
    workingDirectory: '/data/benchmark'

# - task: SSH@0
#   inputs:
#     sshEndpoint: 'vm01srvconn'
#     runOptions: 'inline'
#     inline: |
#       sudo chown -R root:root /data/benchmark/
#       sudo chmod -R 2700 /data/benchmark/
#       sudo chmod -R 700 /data/benchmark/
#     readyTimeout: '20000'
# - task: SSH@0
#   inputs:
#     sshEndpoint: 'vm02srvconn'
#     runOptions: 'inline'
#     inline: |
#       sudo chown -R root:root /data/benchmark/
#       sudo chmod -R 2700 /data/benchmark/
#       sudo chmod -R 700 /data/benchmark/
#     readyTimeout: '20000'
# - task: SSH@0
#   inputs:
#     sshEndpoint: 'vm02srvconn'
#     runOptions: 'inline'
#     inline: |
#       sudo chown -R root:root /data/benchmark/
#       sudo chmod -R 2700 /data/benchmark/
#       sudo chmod -R 700 /data/benchmark/
#     readyTimeout: '20000'
# - task: SSH@0
#   inputs:
#     sshEndpoint: 'vm02srvconn'
#     runOptions: 'commands'
#     commands: 'sudo iperf3 -s -p 8010 2>&1'
#     readyTimeout: '20000'

# - task: SSH@0
#   inputs:
#     sshEndpoint: 'vm01srvconn'
#     runOptions: 'script'
#     scriptPath: 'benchmark/perf_bench.sh'
#     readyTimeout: '20000'


