# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: 'ubuntu-latest'
variables:
- group: Release
steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'
      chmod 600 ./.ssh/terraform_rsa.pem  
      #ssh -i ./.ssh/terraform_rsa.pem -o StrictHostKeyChecking=no azureuser@51.132.233.180 'which ansible'
      
      ssh -i ./.ssh/terraform_rsa.pem -o StrictHostKeyChecking=no azureuser@51.132.233.180 " ansible-playbook \
        --inventory azure_rm.yml \
        users.yml "

      # Write dynamic ansible.cfg.
      echo 'location = "'$(ResourceGroupLocation)'"' | tee terraform.tfvars
      
      ssh -i ./.ssh/terraform_rsa.pem -o StrictHostKeyChecking=no azureuser@51.132.233.180 '

      
    name: 'RunAnsible'
    displayName: 'Run Ansible'
    env:
      ARM_ENDPOINT: $(ARM_ENDPOINT)
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_TENANT_ID: $(ARM_TENANT_ID)
      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)    