
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  # Starter pipeline
- task: SSH@0
  inputs:
    sshEndpoint: 'vm01srvconn'
    runOptions: 'inline'
    inline: |
      sudo mkdir -p /data/benchmark
      sudo chown -R root:root /data/benchmark
      sudo chmod 2700 /data/benchmark
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'vm02srvconn'
    runOptions: 'inline'
    inline: |
      sudo mkdir -p /data/benchmark
      sudo chown -R root:root /data/benchmark
      sudo chmod 2700 /data/benchmark
    readyTimeout: '20000'

