# Performance Benchmarking Script on Centos
# Author: Ozgur Gul (HPE)
# Date: 2021/04/29
# Version: 0.1 (Alpha)

trigger:
- '*'

pr: none

variables:
  buildConfiguration: 'EnvSource'

stages:
  - stage: 'Dev'
    displayName: 'Deploy to the dev environment'
    jobs:
    - job: Provision
      displayName: 'Provision Azure App Service'
      pool:
        vmImage: 'ubuntu-18.04'
      
      variables:
      - group: EnvSource

      steps:
      # Prepare the directory structure on VM-01  
      - task: SSH@0
        displayName: 'Prepare the directory structure on VM-01' 
        inputs:
          sshEndpoint: 'vm01SrvConn'
          runOptions: 'inline'
          inline: |
            echo "Remote User: $(remoteUser)"

            # Prepare landing directory
            sudo mkdir -p /data/benchmark
            sudo chown -R $(remoteUser):$(remoteUser) /data/benchmark
            sudo chmod 2700 /data/benchmark
          readyTimeout: '40000'

      # Prepare the directory structure on VM-02    
      - task: SSH@0
        displayName: 'Prepare the directory structure on VM-02'
        inputs:
          sshEndpoint: 'vm02SrvConn'
          runOptions: 'inline'
          inline: |
            sudo mkdir -p /data/benchmark
            sudo chown -R $(remoteUser):$(remoteUser) /data/benchmark
            sudo chmod 2700 /data/benchmark
          readyTimeout: '40000'

      # Downloads a secure certificate file and installs to ./.ssh folder
      - task: DownloadSecureFile@1
        name: sshPrivFile
        displayName: 'Download SSH Private Key File '
        inputs:
          secureFile: 'terraform_rsa.pem'
 
      # Soft linking 
      - task: Bash@3
        displayName: 'Soft linking the priv key file'
        inputs:
          targetType: 'inline'
          script: |
              # Move the pem file
              echo "This is me: $(id)" 

              echo "Copying $(sshPrivFile.secureFilePath) to the Temp directory..."
              sudo cp $(sshPrivFile.secureFilePath) $(Agent.TempDirectory)
              sudo chmod 600 $(Agent.TempDirectory)/terraform_rsa.pem
              
      # CopyFilesOverSSH on vm-01
      - task: Bash@3
        displayName: 'CopyFilesOverSSH on vm-01'
        inputs:
          targetType: 'inline'
          script: |
            # Write for VM-01 Preparation
            TARGET_SERVER=$(tgtServer01)
            REMOTE_USER=$(remoteUser)
            SSH_KEY_FILE=$(Agent.TempDirectory)/terraform_rsa.pem

            echo "FIO_SIZE=$(fioSize)"                          | tee ./benchmark/.env 
            echo "FIO_OFFSET_INCREMENT=$(fioOffsetIncrement)"   | tee -a ./benchmark/.env 
            echo "FIO_DIRECT=$(fioDirect)"                      | tee -a ./benchmark/.env
            echo "FIO_BENCH_QUICK=$(fioBenchQuick)"             | tee -a ./benchmark/.env
            echo "RUN_IPERF=$(runIperf)"                        | tee -a ./benchmark/.env
            echo "IPERF_REMOTE_SERVER=$(iperfRemoteServer02)"   | tee -a ./benchmark/.env
            echo "IPERF_PORT= $(iperfPort)"                     | tee -a ./benchmark/.env
            
            # Avoid Pem file is too open
            chmod 0600 $SSH_KEY_FILE
            
            ## REMOVE when ready
            ls -al ./benchmark/ 
          
            ssh -q -i $SSH_KEY_FILE -o StrictHostKeyChecking=no $REMOTE_USER@$TARGET_SERVER "date"
            
            # copy using ssh keys from agent to target machine
            # to see the transfer progress
            # ... -e "ssh -q -i $SSH_KEY_FILE" --progress ./benchmark/ ...
            rsync -q -av -e "ssh -q -i $SSH_KEY_FILE" --progress ./benchmark/  $REMOTE_USER@$TARGET_SERVER:/data/benchmark/

            ssh -q -i $SSH_KEY_FILE -o StrictHostKeyChecking=no -T $REMOTE_USER@$TARGET_SERVER <<'EOSSH'
            
            # Change Permissions
            sudo chown -R root:root /data/benchmark/
            sudo chmod -R 2700 /data/benchmark/
            sudo chmod -R 700 /data/benchmark/
            
            # List the content 
            VAR1=`ls -al /data/benchmark`
            echo "$VAR1"

            EOSSH
        env:
          SSH_KEY_FILE: "./.ssh/terraform_rsa.pem"

      # CopyFilesOverSSH on vm-02
      - task: Bash@3
        displayName: 'CopyFilesOverSSH on vm-02'
        inputs:
          targetType: 'inline'
          script: |
            # Write for VM-02 Preparation
            TARGET_SERVER=$(tgtServer02)
            REMOTE_USER=$(remoteUser)
            SSH_KEY_FILE=$(Agent.TempDirectory)/terraform_rsa.pem
            
            echo "FIO_SIZE=$(fioSize)"                          | tee ./benchmark/.env 
            echo "FIO_OFFSET_INCREMENT=$(fioOffsetIncrement)"   | tee -a ./benchmark/.env 
            echo "FIO_DIRECT=$(fioDirect)"                      | tee -a ./benchmark/.env
            echo "FIO_BENCH_QUICK=$(fioBenchQuick)"             | tee -a ./benchmark/.env
            echo "RUN_IPERF=$(runIperf)"                        | tee -a ./benchmark/.env
            echo "IPERF_REMOTE_SERVER=$(iperfRemoteServer01)"   | tee -a ./benchmark/.env
            echo "IPERF_PORT= $(iperfPort)"                     | tee -a ./benchmark/.env
            
            # Pem file is too open
            chmod 0600 $SSH_KEY_FILE
            
            ## REMOVE when ready
            ls -al ./benchmark/ 
          
            ssh -q -i $SSH_KEY_FILE -o StrictHostKeyChecking=no $REMOTE_USER@$TARGET_SERVER "date"
            
            # copy using ssh keys from agent to target machine
            # to see the transfer progress
            # ... -e "ssh -q -i $SSH_KEY_FILE" --progress ./benchmark/ ...
            rsync -q -av -e "ssh -q -i $SSH_KEY_FILE" --progress ./benchmark/  $REMOTE_USER@$TARGET_SERVER:/data/benchmark/

            ssh -q -i $SSH_KEY_FILE -o StrictHostKeyChecking=no -T $REMOTE_USER@$TARGET_SERVER <<'EOSSH'
            
            # Change Permissions
            sudo chown -R root:root /data/benchmark/
            sudo chmod -R 2700 /data/benchmark/
            sudo chmod -R 700 /data/benchmark/
            
            # List the content 
            VAR1=`ls -al /data/benchmark`
            echo "$VAR1"

            EOSSH
        env:
          SSH_KEYFILE: "./.ssh/terraform_rsa.pem"
          

      - task: SSH@0
        displayName: 'Start the iperf on vm-02 at the background'
        inputs:
          sshEndpoint: 'vm02SrvConn'
          runOptions: 'commands'
          commands: 'sudo iperf3 -s -p 8010 2>&1 &'
          readyTimeout: '20000'

      # - task: SSH@0
      #   inputs:
      #     sshEndpoint: 'vm01srvconn'
      #     runOptions: 'script'
      #     scriptPath: 'benchmark/perf_bench.sh'
      #     readyTimeout: '20000'


