trigger:
  - '*'
  
variables:
  buildConfiguration: 'Release'

- stage: 'Dev'
  displayName: 'Deploy to the dev environment'
  jobs:
  - job: Provision
    displayName: 'Provision Azure App Service'
    pool:
      vmImage: 'ubuntu-18.04'
    variables:
    - group: Release
    steps:
    - script: |
        # Exit when any command returns a failure status.
        set -e

        # Write terraform.tfvars.
        echo 'location = "'$(ResourceGroupLocation)'"' | tee terraform.tfvars
        echo 'vm_count = "'$(VmCount)'"' | tee -a terraform.tfvars
        echo 'vm_image_string = "'$(VmImageString)'"' | tee -a terraform.tfvars
        echo 'vm_size = "'$(VmSize)'"' | tee -a terraform.tfvars
        echo 'rg_tag = "'$(RgTag)'"' | tee -a terraform.tfvars
        echo 'admin_username = "'$(AdminUsername)'"' | tee -a terraform.tfvars
        echo 'admin_password = "'$(AdminPassword)'"' | tee -a terraform.tfvars
        
        # Write backend.tfvars.
        echo 'resource_group_name = "'$(ResourceGroupName)'"'  | tee backend.tfvars
        echo 'storage_account_name = "'$(StorageAccountName)'"' | tee -a backend.tfvars
        echo 'container_name = "tfstate"' | tee -a backend.tfvars
        echo 'key = "terraform.tfstate"' | tee -a backend.tfvars

        # Initialize Terraform.
        terraform init -input=false -backend-config="backend.tfvars"

        # Apply the Terraform plan.
        terraform apply -input=false -auto-approve

        # Get the Analytics name for the dev environment.
        AnalyticsHostname=$(terraform output hostname) 
        AnalyticsAddress=$(terraform output public_ip_address) 


        # Write the WebAppNameDev variable to the pipeline.
        echo "##vso[task.setvariable variable=AnalyticsHostname;isOutput=true]$AnalyticsHostname"
        echo "##vso[task.setvariable variable=AnalyticsAddress;isOutput=true]$AnalyticsAddress"

        # Apply the Terraform destroy.
        # terraform destroy -input=false -auto-approve

      name: 'RunTerraform'
      displayName: 'Run Terraform'
      env:
        #ARM_ENDPOINT: $(ARM_ENDPOINT)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
  - deployment: deploy
    dependsOn: Provision
    variables:
      # map the output variable from A into this job
      WebAppNameDev: $[ dependencies.Provision.outputs['RunTerraform.WebAppNameDev'] ]
    pool:
      vmImage: 'ubuntu-18.04'
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo $(WebAppNameDev) # this step uses the mapped-in variable
            name: echovar
          - script: |
              echo "##vso[task.setvariable variable=WebAppName;]$(WebAppNameDev)"
            displayName: 'Run a one-line script'
          - script: |
              echo $(WebAppName) 
            displayName: '=== DEBUG LINE ==='   
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website'
            inputs:
              azureSubscription: 'Resource Manager - Tailspin - Space Game'
              ##[error]Error: Resource '"tailspin-space-game-web-dev-2444"' doesn't exist. Resource should exist before deployment.
              appName: $(WebAppName)
              # as a workaround I had to hardcode App Name
              #appName: 'tailspin-space-game-web-dev-2444'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
